import re
from os import walk
import os

#run in the base directory
ignore_dirs = [".github", ".git"]
author_pat = r'AUTHOR:(.*?);'
title_pat = r'TITLE:(.*?);'
prep_pat = r'PREP:(.*?);'
cook_pat = r'COOK:(.*?);'

def as_html(md_file):
    return md_file[:-3]+".html"

for (dirpath, dirnames, filenames) in walk(os.getcwd()):
    folder_name = dirpath[dirpath.rindex("/")+1:]
    if ".github" in dirpath or ".git" in dirpath or folder_name=="recipes":
        continue
    md_file = "<!-- AUTOGENERATED DO NOT ALTER -->\n"
    
    print("Generating index:", folder_name)
    md_file+="<title>"+folder_name+"</title>\n"
    md_file+="| Title | Prep Time | Cook Time | Author |\n| :---: | :-------: | :-------: | :----: |\n"
    md_path = dirpath+"/index.md"
    print(dirpath)
    for file in filenames:
        if ".md" in file and not "index" in file:
            with open(dirpath+"/"+file, 'r') as f:
                fcontents = f.read()
                author_match = re.findall(author_pat, fcontents)
                title_match = re.findall(title_pat, fcontents)
                prep_match = re.findall(prep_pat, fcontents)
                cook_match = re.findall(cook_pat, fcontents)
                author = author_match[0] if author_match else "anon";
                title = title_match[0] if title_match else file;
                prep = prep_match[0] if prep_match else "???";
                cook = cook_match[0] if cook_match else "???";

            print(author, title, prep, cook)
            md_file+="| ["+title+"]("+as_html(file)+") | "+prep+" | "+cook+" | "+author+" |\n"
    print(md_file)
    with open(md_path, 'w') as out_file:
        out_file.write(md_file)






