name: Pandoc build and PR


# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FOLDER_LIST: "./crockpot ./dessert ./breakfast ./lunch ./dinner"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Get list of changed files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
      - name: Generate index.md files
        run: python indexgen.py
      - name: Find Changed files
        run: echo "CHANGED_FILES="$(find -type f -name "*.md")"" >> $GITHUB_ENV
        shell: bash
      - name: Move diff files
        run: |
          mkdir output
          for f in $FOLDER_LIST;
          do
            mkdir output/$f
          done
          mv styling.css output/styling.css
          for f in $CHANGED_FILES;
          do
            mv $f output/$f
          done
          echo $CHANGED_FILES > output/changed.txt
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
  Pandoc build:
    needs: Get list of changed files
    container: pandoc/core:2.9
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Artifact files
        uses: actions/download-artifact@master
        with:
          name: output
      - name: Make output folders
        run: |
          mkdir build
          for f in $FOLDER_LIST;
          do
            mkdir build/$f
          done
          mv styling.css build/styling.css
      - name: Run pandoc
        run: |
          CHANGED_FILES=`cat changed.txt`
          for f in $CHANGED_FILES;
          do
            pandoc --standalone --css=https://githubrecipes.com/styling.css --to=html5 "$f" -o "./build/${f:0:-3}.html"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  Open PR on github pages repo:
    needs: Pandoc build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github pages repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: githubrecipes/githubrecipes.github.io
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Open PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          
      
        
      
      
      
                
                
