name: Pandoc build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pandoc_build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          echo "set-env name=FILELIST::$(printf '"%s" ' *.md ./*/*.md)"
          
      
      - uses: docker://pandoc/core:2.9
      - run: |
          for f in $FILELIST;
          do pandoc -s --css=styling.css --to=html5 $f --output build/$f;
          done
#        with:
#          args: >-
#                --standalone
#                --css=styling.css
#                --to=html5
#                ${{ env.FILELIST }}
#                --output=build/${{ env.FILELIST }}  
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
                
                
