name: Pandoc build


# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    container: pandoc/core:2.9
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find Markdown files
        run: echo "MARKDOWN_FILES=$(find -type f -name "*.md")" >> $GITHUB_ENV
        shell: bash
      - name: Move diff files
        run: |
          mkdir output
          for f in $FOLDER_LIST;
          do
            mkdir output/$f
          done
          for f in $MARKDOWN_FILES;
          do
            pandoc --standalone --css=styling.css --to=html5 "$f" -o "./output/${f:0:-2}.html)"
          done
        env:
          FOLDER_LIST: "./crockpot ./dessert"
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
                
                
                
